// Writes docs/state-programs.md: every state's scenic byway program with a link to the agency, and to the Rambleroo chapter
// where one exists. Generated from content/state-programs.json and content/states/*.json, so rerun it after adding a chapter.
// Usage: npx tsx scripts/states/write-programs-doc.ts
import { readdir, readFile, writeFile } from 'node:fs/promises'
import type { StateChapter } from '../../src/lib/types.ts'

const ROOT = new URL('../../', import.meta.url)
interface Program {
  code: string
  state: string
  program: string | null
  agency: string
  programUrl: string | null
  gisLayer?: string | null
}

const programs: Program[] = JSON.parse(await readFile(new URL('content/state-programs.json', ROOT), 'utf8'))
const chapters = new Map<string, StateChapter>()
for (const file of await readdir(new URL('content/states/', ROOT))) {
  if (!file.endsWith('.json')) continue
  const chapter: StateChapter = JSON.parse(await readFile(new URL(`content/states/${file}`, ROOT), 'utf8'))
  chapters.set(chapter.code, chapter)
}

const cell = (s: string) => s.replaceAll('|', '\\|')
// Some states have no verified program page (or no separate state tier); say so instead of linking a guess.
const program = (p: Program) =>
  p.program && p.programUrl
    ? `[${cell(p.program)}](${p.programUrl})`
    : p.programUrl
      ? `[No separate state program](${p.programUrl})`
      : `${cell(p.program ?? '—')} (no official page found)`
const rows = programs
  .slice()
  .sort((a, b) => a.state.localeCompare(b.state))
  .map((p) => {
    const chapter = chapters.get(p.code)
    const roads = chapter?.programs.reduce((n, program) => n + program.members.length, 0)
    return `| ${p.state} | ${program(p)} | ${cell(p.agency)} | ${p.gisLayer ? `[layer](${p.gisLayer})` : '—'} | ${
      chapter ? `[${roads} roads](https://rambleroo.app/state/${p.code})` : '—'
    } |`
  })

const doc = `# State scenic byway programs

Every state designates its own scenic roads, usually through its department of transportation. This page links each state's program, the agency that runs it, the official route layer where the state publishes one, and the Rambleroo chapter where one has been written (${chapters.size} of ${programs.length} so far). How chapters are made, and what is still to do, is in [state-coverage.md](state-coverage.md).

Generated by \`scripts/states/write-programs-doc.ts\` from \`content/state-programs.json\` and \`content/states/\`; edit those, not this file.

| State | Program | Agency | Route layer | Chapter |
| --- | --- | --- | --- | --- |
${rows.join('\n')}
`
await writeFile(new URL('docs/state-programs.md', ROOT), doc)
console.log(`wrote ${programs.length} states, ${chapters.size} chapters`)
